//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationWorkingHour
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Time { get; set; }
        public string ArabicName { get; set; }
        public string ArabicTime { get; set; }
        public Nullable<int> LocationID { get; set; }
    }
}
