//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagesInfo
    {
        public int PackageInfoID { get; set; }
        public string PackageName { get; set; }
        public Nullable<decimal> PackagePrice { get; set; }
        public string PackageDescription { get; set; }
        public Nullable<int> DeviceCount { get; set; }
        public Nullable<int> LocationsLimit { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsInventory { get; set; }
        public Nullable<bool> IsGarageGo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
