//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportReview
    {
        public int ReportReveiwID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Reason { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LikeStatus { get; set; }
        public Nullable<int> LikeValue { get; set; }
        public Nullable<int> DisLikeValue { get; set; }
    }
}
