//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplianceDevice
    {
        public int ComplianceDeviceID { get; set; }
        public string ModelNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string UserValue { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
