//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Garage_Entities : DbContext
    {
        public Garage_Entities()
            : base("name=Garage_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSource> AppSources { get; set; }
        public virtual DbSet<Bay> Bays { get; set; }
        public virtual DbSet<CarInspection> CarInspections { get; set; }
        public virtual DbSet<CarInspectionDetail> CarInspectionDetails { get; set; }
        public virtual DbSet<CarNote> CarNotes { get; set; }
        public virtual DbSet<CarNotesImage> CarNotesImages { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyClient> CompanyClients { get; set; }
        public virtual DbSet<CompanyInvoice> CompanyInvoices { get; set; }
        public virtual DbSet<CompanyInvoiceDetail> CompanyInvoiceDetails { get; set; }
        public virtual DbSet<CompanyQuotation> CompanyQuotations { get; set; }
        public virtual DbSet<CompanyQuotationDetail> CompanyQuotationDetails { get; set; }
        public virtual DbSet<ComplianceDevice> ComplianceDevices { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CreditCustomer> CreditCustomers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<DiscountItem> DiscountItems { get; set; }
        public virtual DbSet<ImageLocation> ImageLocations { get; set; }
        public virtual DbSet<Integration> Integrations { get; set; }
        public virtual DbSet<IntegrationActivation> IntegrationActivations { get; set; }
        public virtual DbSet<inv_Bill> inv_Bill { get; set; }
        public virtual DbSet<inv_BillDetail> inv_BillDetail { get; set; }
        public virtual DbSet<inv_PurchaseOrder> inv_PurchaseOrder { get; set; }
        public virtual DbSet<inv_PurchaseOrderDetail> inv_PurchaseOrderDetail { get; set; }
        public virtual DbSet<inv_Reconciliation> inv_Reconciliation { get; set; }
        public virtual DbSet<inv_ReconciliationDetail> inv_ReconciliationDetail { get; set; }
        public virtual DbSet<inv_Stock> inv_Stock { get; set; }
        public virtual DbSet<inv_StockIssue> inv_StockIssue { get; set; }
        public virtual DbSet<inv_StockIssueDetail> inv_StockIssueDetail { get; set; }
        public virtual DbSet<inv_StockRequest> inv_StockRequest { get; set; }
        public virtual DbSet<inv_StockRequestDetail> inv_StockRequestDetail { get; set; }
        public virtual DbSet<inv_StockStore> inv_StockStore { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<LocationAmenitiesJunc> LocationAmenitiesJuncs { get; set; }
        public virtual DbSet<LocationImage> LocationImages { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationServiceJunc> LocationServiceJuncs { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Modifier> Modifiers { get; set; }
        public virtual DbSet<OrderCheckout> OrderCheckouts { get; set; }
        public virtual DbSet<OrderCheckoutDetail> OrderCheckoutDetails { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderDetail_FM> OrderDetail_FM { get; set; }
        public virtual DbSet<OrderDetailPackage> OrderDetailPackages { get; set; }
        public virtual DbSet<OrderInspectionMapping> OrderInspectionMappings { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrdersChecklist> OrdersChecklists { get; set; }
        public virtual DbSet<PackageDetail> PackageDetails { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReportLog> ReportLogs { get; set; }
        public virtual DbSet<Role_Forms> Role_Forms { get; set; }
        public virtual DbSet<Role_Group> Role_Group { get; set; }
        public virtual DbSet<Role_GroupForms> Role_GroupForms { get; set; }
        public virtual DbSet<SalesItem> SalesItems { get; set; }
        public virtual DbSet<SalesSetting> SalesSettings { get; set; }
        public virtual DbSet<SessionInfo> SessionInfoes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<SubUser> SubUsers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ZatcaAuthentication> ZatcaAuthentications { get; set; }
        public virtual DbSet<ZohoChartOfAccount> ZohoChartOfAccounts { get; set; }
        public virtual DbSet<ZohoCOAMapping> ZohoCOAMappings { get; set; }
        public virtual DbSet<ZohoSetting> ZohoSettings { get; set; }
    
        [DbFunction("Garage_Entities", "Split")]
        public virtual IQueryable<Split_Result> Split(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[Garage_Entities].[Split](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    }
}
