//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountItem
    {
        public int ItemDiscountID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string Type { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Item Item { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
