//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationActivation
    {
        public int IntegrationActivationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActivateAdmin { get; set; }
        public Nullable<bool> IsActivateUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
