//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_Reconciliation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_Reconciliation()
        {
            this.inv_ReconciliationDetail = new HashSet<inv_ReconciliationDetail>();
        }
    
        public int ReconciliationID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_ReconciliationDetail> inv_ReconciliationDetail { get; set; }
    }
}
