//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PartialPaymentID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<double> ReceiveAmount { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PayBy { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
