//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPackageDetail
    {
        public int UserPackageDetailID { get; set; }
        public Nullable<int> PackageInfoID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual PackagesInfo PackagesInfo { get; set; }
        public virtual UserPackageDetail UserPackageDetails1 { get; set; }
        public virtual UserPackageDetail UserPackageDetail1 { get; set; }
        public virtual User User { get; set; }
    }
}
