//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZatcaAuthentication
    {
        public int AuthenicationID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string InvoiceType { get; set; }
        public string CSR { get; set; }
        public string PKey { get; set; }
        public string Certificate { get; set; }
        public string Secret { get; set; }
        public string UserValue { get; set; }
    }
}
