//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZohoCOAMapping
    {
        public int COAMappingID { get; set; }
        public Nullable<int> COATotalSales { get; set; }
        public Nullable<int> COADiscount { get; set; }
        public Nullable<int> COAReturn { get; set; }
        public Nullable<int> COAVAT { get; set; }
        public Nullable<int> COACashSales { get; set; }
        public Nullable<int> COACardSales { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
