//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZohoSetting
    {
        public int ZohoSettingID { get; set; }
        public string client_secret { get; set; }
        public string client_id { get; set; }
        public string Permisions { get; set; }
        public string authToken { get; set; }
        public string organization_id { get; set; }
        public Nullable<bool> IsAuthorize { get; set; }
        public Nullable<bool> IsActivateAdmin { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
